#!/bin/bash

sed -e 's/\s*\([\+0-9a-zA-Z]*\).*/\1/' << EOF | fdisk /dev/sdc
  g # clear the in memory partition table
  n # new partition
  1 # partition number
    # default - start at beginning
  +512M # 512 MB boot partition
  n # new partition
  2 # partition number
    # default - start at beginning
    # default -end of device
  t # change type of partition
  1 # change partition 1 type
  1 # make it an EFI partition
  w # write partition table
  q # finished
EOF 


