#!/bin/bash

mount /dev/sdc2 /mnt
mkdir /mnt/boot/EFI
mount /dev/sdc1 /mnt/boot/EFI
arch-chroot /mnt/ grub-install --target=x86_64-efi --bootloader-id=BOOT --recheck
mv /mnt/boot/EFI/EFI/BOOT/grubx64.efi /mnt/boot/EFI/EFI/BOOT/BOOTX64.EFI

cp grub /mnt/etc/default/grub

arch-chroot /mnt/ grub-mkconfig -o /boot/grub/grub.cfg
